[package]
name = "robo-remote"
version = "0.1.0"
authors = ["Esa Varemo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.24.0"
serialport = "3.3.0"
